CREATE TABLE "public"."tb_person" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "first_name" VARCHAR(16) NOT NULL,
  "last_name" VARCHAR(16) NOT NULL,
  "address" VARCHAR(124) NOT NULL,
  "gender" VARCHAR(12) NOT NULL,
  CONSTRAINT "tb_person_pkey" PRIMARY KEY ("id")
);
